[package]
name = "synql-builders-metadata"
version = "0.1.0"
edition.workspace = true

[dependencies]
synql-core.workspace = true
synql-insertable.workspace = true
synql-diesel-schema.workspace = true
synql-models.workspace = true
syn.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
