[package]
name = "sql_traits"
version = "0.1.0"
edition.workspace = true

[dependencies]
sqlparser.workspace = true
common_traits.workspace = true
graph.workspace = true
algebra.workspace = true
csqlv.workspace = true
rayon.workspace = true

[lints]
workspace = true
