[package]
name = "synql-relations"
version = "0.1.0"
edition = "2024"

[dependencies]
synql-core.workspace = true
synql-models.workspace = true
syn.workspace = true
proc-macro2.workspace = true
quote.workspace = true

[lints]
workspace = true
