[package]
name = "core_structures_builder"
version = "0.1.0"
edition.workspace = true

[dependencies]
tokio.workspace = true
time_requirements.workspace = true
quote.workspace = true
serde_json.workspace = true
reference_docker.workspace = true
init_db.workspace = true
common_traits.workspace = true
diesel = { workspace = true, features = ["postgres"] }
anyhow.workspace = true

[lints]
workspace = true
