[package]
name = "synql-checks"
version = "0.1.0"
edition = "2024"

[dependencies]
synql-core.workspace = true
synql-attributes.workspace = true
sql_traits.workspace = true
proc-macro2.workspace = true
syn.workspace = true
quote.workspace = true
sqlparser.workspace = true

[lints]
workspace = true
