[package]
name = "pg_traits"
version = "0.1.0"
edition = "2024"

[dependencies]
pg_diesel.workspace = true
diesel.workspace = true
syn.workspace = true
common_traits.workspace = true
enumflags2.workspace = true

[lints]
workspace = true
