[package]
name = "sql_constraints"
version = "0.1.0"
edition = "2024"

[dependencies]
sqlparser.workspace = true
common_traits.workspace = true
sql_traits.workspace = true
inflector.workspace = true
snake_case_sanitizer.workspace = true

[lints]
workspace = true
