[package]
name = "yew_form"
version = "0.2.0"
authors = ["J-F Bilodeau <jfbilodeau@chronogears.com>"]
edition = "2018"
description = "Bringing MVC to Yew! A set mildly opinionated Yew component to map and validate a model to a HTML form"
license = "MIT"
repository = "https://github.com/jfbilodeau/yew_form"
readme = "../README.md"
categories = [ "web-programming" ]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
validator = "0.16.1"
validator_derive = "0.16.0"
yew = "0.21.0"
web-sys = "0.3.66"
