[package]
name = "elements-rs"
version = "0.1.0"
authors.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
description = "A comprehensive library for chemical elements and their isotopes with rich metadata"
readme = "README.md"
keywords = ["chemistry", "periodic-table", "elements", "isotopes", "science"]
categories = ["science", "database"]
include = ["src/**/*", "Cargo.toml", "README.md", "LICENSE"]

[lib]
crate-type = ["cdylib", "lib"]

# [[bin]]
# name = "pgrx_embed_elements"
# path = "./src/bin/pgrx_embed.rs"

[dependencies]
serde = { workspace = true, optional = true }
pgrx = { workspace = true, optional = true }
diesel = { workspace = true, optional = true }
strum_macros.workspace = true
strum.workspace = true
diesel_pgrx = { workspace = true, optional = true }
multi_ranged.workspace = true


[features]
default = ["serde"]
serde = ["dep:serde"]
diesel = ["dep:diesel"]
sqlite = ["diesel", "diesel/sqlite", "diesel_pgrx/sqlite"]
postgres = ["diesel", "diesel/postgres", "diesel_pgrx/postgres"]
diesel_pgrx = ["diesel", "dep:diesel_pgrx"]
pgrx = ["dep:pgrx"]
pg13 = ["pgrx", "pgrx/pg13"]
pg14 = ["pgrx", "pgrx/pg14"]
pg15 = ["pgrx", "pgrx/pg15"]
pg16 = ["pgrx", "pgrx/pg16"]
pg17 = ["pgrx", "pgrx/pg17"]

[lints]
workspace = true
