[package]
name = "synql"
version = "0.1.0"
edition.workspace = true

[dependencies]
common_traits.workspace = true
sql_traits.workspace = true
sql_relations.workspace = true
syn.workspace = true
synql-core.workspace = true
synql-models.workspace = true
synql-diesel-schema.workspace = true
synql-relations.workspace = true
synql-attributes.workspace = true
synql-insertable.workspace = true
synql-builders.workspace = true
synql-value-settable.workspace = true
synql-insertable-key-settable.workspace = true
synql-buildable-key-settable.workspace = true
synql-transitive-extension.workspace = true
chrono.workspace = true
time_requirements.workspace = true

[dev-dependencies]
graph.workspace = true
tempfile.workspace = true
insta.workspace = true
sql_constraints.workspace = true

[lints]
workspace = true
