[package]
name = "synql"
version = "0.1.0"
edition.workspace = true

[dependencies]
common_traits.workspace = true
sql_traits.workspace = true
sql_relations.workspace = true
syn.workspace = true
chrono.workspace = true
time_requirements.workspace = true

[dev-dependencies]
graph.workspace = true
tempfile.workspace = true
insta.workspace = true
sql_constraints.workspace = true

[lints]
workspace = true
