[package]
name = "diesel_migrations_utils"
version = "0.1.0"
edition.workspace = true

[dependencies]
sqlparser.workspace = true
diesel.workspace = true
graph.workspace = true
algebra.workspace = true

[lints]
workspace = true
