[package]
name = "synql-builders"
version = "0.1.0"
edition = "2024"

[dependencies]
sql_traits.workspace = true
synql-core.workspace = true
synql-models.workspace = true
synql-diesel-schema.workspace = true
synql-insertable.workspace = true
synql-attributes.workspace = true
synql-builders-metadata.workspace = true
synql-insertable-key-settable.workspace = true
synql-buildable-key-settable.workspace = true
sql_relations.workspace = true
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true

[lints]
workspace = true
