[package]
name = "synql-attributes"
version = "0.1.0"
edition = "2024"

[dependencies]
sql_traits.workspace = true
synql-core.workspace = true
synql-diesel-schema.workspace = true
quote.workspace = true
proc-macro2.workspace = true
syn.workspace = true

[lints]
workspace = true
