[package]
name = "mermaid"
version = "0.1.0"
edition.workspace = true

[dependencies]
serde = { workspace = true, optional = true }
common_traits.workspace = true
colorsys.workspace = true

[features]
default = ["serde"]
serde = ["dep:serde", "common_traits/serde"]

[lints]
workspace = true
