[package]
name = "synql-models"
version = "0.1.0"
edition.workspace = true

[dependencies]
sql_traits.workspace = true
synql-core.workspace = true
synql-diesel-schema.workspace = true
quote.workspace = true
proc-macro2.workspace = true

[lints]
workspace = true
