[package]
name = "elements_builder"
version = "0.1.0"
edition.workspace = true

[dependencies]
syn.workspace = true
quote.workspace = true
serde.workspace = true
proc-macro2.workspace = true
serde_json.workspace = true
