[package]
name = "pg_diesel"
version = "0.1.0"
edition.workspace = true

[dependencies]
diesel = { workspace = true, features = ["postgres", "128-column-tables"] }
serde = { workspace = true, optional = true }
sql_traits.workspace = true
common_traits.workspace = true
sqlparser.workspace = true

[dev-dependencies]
tokio.workspace = true
reference_docker.workspace = true
synql-models.workspace = true
synql-diesel-schema.workspace = true
synql-core.workspace = true
quote.workspace = true

[lints]
workspace = true

[features]
default = []
serde = ["dep:serde"]
