[package]
name = "diesel-queries"
version = "0.1.0"
edition.workspace = true

[dependencies]
validation_errors.workspace = true
common_traits.workspace = true
diesel.workspace = true

[lints]
workspace = true
